FROM python:3.12-slim AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential gcc libpq-dev curl && \
    rm -rf /var/lib/apt/lists/*

ARG APP_USER=app
ARG APP_UID=1001
ARG APP_GID=1001
RUN groupadd -g ${APP_GID} ${APP_USER} \
 && useradd  -m -u ${APP_UID} -g ${APP_GID} -s /bin/bash ${APP_USER}

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN pip install --no-cache-dir poetry==1.8.2 \
 && poetry config virtualenvs.in-project true \
 && poetry install --no-interaction --no-ansi --no-root

COPY . /app
RUN chown -R ${APP_USER}:${APP_USER} /app


USER ${APP_UID}

CMD ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
